### ISSUE TITLE
DCOS 1.9 linkerd-viz never deploys

### ISSUE THREAD

**Issue by DarkBlaez** [linkerd/linkerd-viz#29]
Have tried to deploy in DCOS using the universe package. Results in the service never deploying or running. I have looked on each node for the docker image buoyantio/linkerd-viz. No image has been pulled. I have also tried this from using just the json and creating a service from it and the result is the same. Not sure where else to look to resolve this. Not urgent but certainly would like to see this working in 1.9

**Comment by siggy** [comment]
Thanks for the report @DarkBlaez ! We have DC/OS deploying in 1.9, both via the universe and as custom packages.

Can you provide a bit more description of what you are seeing? Does it get stuck during deployment? What do `dcos marathon app list` and `dcos marathon deployment list` show?

**Comment by DarkBlaez** [comment]
I've abandoned DCOS at this time given the issues I've seen in 1.9. Will strike it up perhaps in a few months and see what has changed

**Comment by siggy** [comment]
closing this for now. if you or anyone else hits any issues with dc/os 1.9, please reopen.
