### ISSUE TITLE
Q: communication to/from linkerd with enabled tls

### ISSUE THREAD

**Issue by torstello** [linkerd/linkerd-viz#31]
I'm working through some linkerd examples from your blog.
If I use the [linkerd-ingress-controller](https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/linkerd-ingress-controller.ymll) (without using tls) linkerd-viz works.

But if i switch to [linkerd-tls-ingress-controller](https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/linkerd-tls-ingress-controller.yml) prometheus doesn't get any data.

Is there a way to adjust the config that it also works with tls enabled communication?

**Comment by wmorgan** [comment]
Any errors in the logs? Which linkerd version?

**Comment by torstello** [comment]
I re-deployed all  components again and now it works.

maybe i mixed something up last time playing through multiple examples, sorry for that!

**Comment by wmorgan** [comment]
No worries! Please let us know if you run into any other issues.
