### ISSUE TITLE
Consul startup doc error

### ISSUE THREAD

**Issue by dlaidlaw** [linkerd/linkerd-viz#38]
The Readme for the Consul Deploy says to start Consul with docker in host networking mode, then start the linkerd-vis docker container without host networking mode. This will not work because the linkerd-vis configuration for consul is set to use localhost:8500. The localhost will not work unless the linkerd-vis container is also run in host networking mode.

**Comment by siggy** [comment]
Nice catch @dlaidlaw, fix is up: #39.
