### ISSUE TITLE
Share dashboard configurations on Grafana.com

### ISSUE THREAD

**Issue by activeshadow** [linkerd/linkerd-viz#46]
Grafana.com provides a central repository of popular dashboards. It would be great to see `linkerd-health-dashboard.json` and `linkerd-viz-dashboard.json` available there.

**Comment by siggy** [comment]
@activeshadow interesting idea! we'll take a look.

**Comment by siggy** [comment]
Dashboards are now public:
https://grafana.com/dashboards/3983
https://grafana.com/dashboards/3986

FYI, making these dashboards public required add `__requires` sections to each dashboard:
https://github.com/linkerd/linkerd-viz/commit/7fd012c7d2884b4c511737f9686e64c2badd9249
