### ISSUE TITLE
improvement for documentaiton regarding grafana

### ISSUE THREAD

**Issue by uwebartels** [linkerd/linkerd-viz#62]
Hi,

the parameter grafana.url is not well documented.

I installed as described linkerd-viz + grafana from the helm chart in the same namespace.
So for grafana.url I configured http://grafana, http://grafana/, but I get only a 502 in return for the grafana links.

what happed?
Linkerd-viz does something with the url and produces error log entries like
2023/03/14 10:09:15 http: proxy error: dial tcp: lookup http://grafana: no such host
2023/03/14 10:19:15 http: proxy error: dial tcp: lookup http://grafana/: no such host
depending on the configuration.

So I eneded up in reading https://linkerd.io/2.12/tasks/grafana/index.html and use the configuration `grafana:80` from the example.

Something is wrong in the rewriting or the documentation needs an update.

Best...
Uwe

**Comment by siggy** [comment]
Hi @uwebartels. This repo is for the Linkerd 1 viz integration. Recommend reaching out in slack.linkerd.io, or, file an issue in the https://github.com/linkerd/linkerd2 repo.

I'm going to close this issue.
